name: dockerhub
on:
  push:
    branches:
      - "main"
      - "6-Create-Docker-Automations"

env:
  DOCKER_TAG: ""
  DOCKER_REPO: "abiddiscombe/concierge"

jobs:
  DockerBuildAndPush:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Get Latest SemVer Tag"
        id: currentSemVer
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: v

      - name: "Specify Image Tag"
        run: echo "DOCKER_TAG=${{ env.DOCKER_REPO }}:${{ steps.currentSemVer.outputs.tag }}-test" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_TAG }}
